CREATE TABLE IF NOT EXISTS keywords (id INT AUTO_INCREMENT PRIMARY KEY, keyword VARCHAR(100) NOT NULL, category ENUM('skill', 'job_title', 'experience_level', 'education_field', 'certification', 'technology') NOT NULL);
INSERT INTO keywords (keyword, category) VALUES ('PHP', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('MySQL', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('JavaScript', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('HTML', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('CSS', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('React', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Node.js', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Laravel', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Python', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Django', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Java', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Spring Boot', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('C++', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('C#', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Git', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('REST API', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('GraphQL', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('SQL', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('NoSQL', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Machine Learning', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Data Analysis', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('R', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Scala', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('TensorFlow', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Keras', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Bootstrap', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('SASS', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('LESS', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Flask', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('FastAPI', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Vue.js', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Angular', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('TypeScript', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Redux', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Next.js', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Nuxt.js', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Webpack', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Babel', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Tailwind CSS', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('JQuery', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('AJAX', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('XML', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('JSON', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Linux', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Bash', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('PowerShell', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('JIRA', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Agile', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Scrum', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('CI/CD', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Unit Testing', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Integration Testing', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Mocha', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Chai', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Jest', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Selenium', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Cypress', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Postman', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Figma', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Adobe XD', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Sketch', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('UI Design', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('UX Design', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Design Thinking', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Accessibility', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Responsive Design', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Firebase', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Supabase', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('MongoDB', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('PostgreSQL', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('SQLite', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Elasticsearch', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Redis', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('GraphDB', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Neo4j', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Jenkins', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Docker', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Kubernetes', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('AWS', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Azure', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Google Cloud', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Terraform', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Ansible', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Nagios', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Splunk', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Prometheus', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Grafana', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Logstash', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('New Relic', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Matplotlib', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Pandas', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('NumPy', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('OpenCV', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('NLP', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('ChatGPT', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('LangChain', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Blockchain', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Solidity', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Smart Contracts', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Web3.js', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Truffle', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Hardhat', 'skill');
INSERT INTO keywords (keyword, category) VALUES ('Software Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Web Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Frontend Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Backend Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Full Stack Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Data Analyst', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Data Scientist', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('DevOps Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Project Manager', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('QA Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Mobile Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Android Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('iOS Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Cloud Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Site Reliability Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('ML Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('AI Researcher', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Systems Analyst', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Business Analyst', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Product Manager', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Scrum Master', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('UI Designer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('UX Designer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Solutions Architect', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Security Analyst', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Penetration Tester', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Network Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Technical Writer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Database Administrator', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Game Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Embedded Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Application Support Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('IT Support Specialist', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('SEO Specialist', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Digital Marketing Analyst', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('CRM Specialist', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('ERP Consultant', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Technical Project Manager', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Data Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('BI Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Research Scientist', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Software Tester', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Quality Assurance Analyst', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Release Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Infrastructure Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Cloud Architect', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('AI Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Customer Support Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('IT Auditor', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Computer Vision Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Platform Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Tools Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Test Automation Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('ETL Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Big Data Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Blockchain Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Robotics Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Cybersecurity Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('AR/VR Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Motion Graphics Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Chatbot Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Smart Contract Auditor', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Web3 Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Machine Vision Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Speech Recognition Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Backend Architect', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Software Architect', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('API Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Firmware Developer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Build Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('CI Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Performance Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Cloud Support Engineer', 'job_title');
INSERT INTO keywords (keyword, category) VALUES ('Intern', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Trainee', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Entry Level', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Junior', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Associate', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Mid-level', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Intermediate', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Senior', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Lead', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Principal', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Manager', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Director', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Executive', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('VP', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Chief Technology Officer', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('CTO', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Chief Information Officer', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('CIO', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Tech Lead', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Engineering Manager', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Head of Engineering', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Product Lead', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Research Intern', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Software Intern', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Graduate Developer', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Apprentice', 'experience_level');
INSERT INTO keywords (keyword, category) VALUES ('Computer Science', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Information Technology', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Software Engineering', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Data Science', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Artificial Intelligence', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Cybersecurity', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Electrical Engineering', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Electronics', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Mathematics', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Physics', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Statistics', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Mechanical Engineering', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Civil Engineering', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Chemical Engineering', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Biomedical Engineering', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Bioinformatics', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Computational Biology', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Business Administration', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Economics', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Finance', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Accounting', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Management Information Systems', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Marketing', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Psychology', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Education', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Linguistics', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Geography', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('History', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Philosophy', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Law', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Political Science', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Sociology', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Anthropology', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Astronomy', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Design', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Visual Arts', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Architecture', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Environmental Science', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('Public Health', 'education_field');
INSERT INTO keywords (keyword, category) VALUES ('AWS Certified Developer', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Google Cloud Certified', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Certified Scrum Master', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('PMP', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Microsoft Certified: Azure Fundamentals', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Oracle Certified Java Programmer', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Cisco Certified Network Associate', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('CompTIA Security+', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('CompTIA A+', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Certified Ethical Hacker', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('ITIL Foundation', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('TOGAF Certified', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('CISSP', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('CISA', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('CISM', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('ISTQB Certified Tester', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('OCJP', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Red Hat Certified Engineer', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Salesforce Administrator', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Adobe Certified Expert', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Google Analytics Individual Qualification', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('HubSpot Inbound Certification', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Docker Certified Associate', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Kubernetes Administrator Certified', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Agile Certified Practitioner', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Certified Blockchain Expert', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('TensorFlow Developer Certificate', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Unity Certified Developer', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('RHCSA', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Certified Jenkins Engineer', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('CI/CD Professional Certification', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('DevOps Foundation Certification', 'certification');
INSERT INTO keywords (keyword, category) VALUES ('Docker', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Kubernetes', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Jenkins', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('GitHub', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Bitbucket', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Slack', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Trello', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Jira', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('VS Code', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Postman', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('AWS', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Azure', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Google Cloud', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Terraform', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Ansible', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Nagios', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Splunk', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Prometheus', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Grafana', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Firebase', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Supabase', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('MongoDB', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('PostgreSQL', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('MySQL', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('SQLite', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Oracle DB', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Microsoft SQL Server', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('DigitalOcean', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Heroku', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Vercel', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Netlify', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Cloudflare', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Nginx', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Apache', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Tomcat', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Kibana', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('ELK Stack', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Zabbix', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('New Relic', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('AppDynamics', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Figma', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Sketch', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Adobe XD', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Photoshop', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Illustrator', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Notion', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Obsidian', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('ChatGPT', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('OpenAI API', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('LangChain', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Stable Diffusion', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Hugging Face', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('FastAPI', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Flask', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Django', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Next.js', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Nuxt.js', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Web3.js', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Truffle', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Solidity', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Hardhat', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Metamask', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Chainlink', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('IPFS', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('BigQuery', 'technology');
INSERT INTO keywords (keyword, category) VALUES ('Snowflake', 'technology');